let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
let age = 18;
console.log("Is age > 16? I predict True.");
console.log(age > 16);
console.log("Is age < 18? I predict False.");
console.log(age < 18);
let isRaining = true;
console.log("Is it raining? I predict True.");
console.log(isRaining);
console.log("Is it sunny? I predict False.");
console.log(!isRaining);
let fruit = 'apple';
console.log("Is fruit not equal to 'banana'? I predict True.");
console.log(fruit !== 'banana');
console.log("Is fruit equal to 'orange'? I predict False.");
console.log(fruit === 'orange');
let temperature = 25;
console.log("Is temperature >= 20? I predict True.");
console.log(temperature >= 20);
console.log("Is temperature < 25? I predict False.");
console.log(temperature < 25);
export {};
